// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bidding.sql

package database

import (
	"context"
	"database/sql"
)

const acceptBid = `-- name: AcceptBid :exec
UPDATE bids
SET status = 'accepted'
WHERE id = $1
`

func (q *Queries) AcceptBid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, acceptBid, id)
	return err
}

const createBid = `-- name: CreateBid :one
INSERT INTO bids(
    id, 
    listing_id, 
    buyer_id, 
    agent_id, 
    amount, 
    status, 
    created_at, 
    previous_bid_id
) VALUES (
    nextval('bids_id_seq'::regclass),
    $1,
    $2,
    $3,
    $4,
    'pending'::"BidStatus",
    now(),
    $5
)
RETURNING id, listing_id, buyer_id, agent_id, amount, status, created_at, previous_bid_id
`

type CreateBidParams struct {
	ListingID     int64         `json:"listing_id"`
	BuyerID       int64         `json:"buyer_id"`
	AgentID       int64         `json:"agent_id"`
	Amount        string        `json:"amount"`
	PreviousBidID sql.NullInt64 `json:"previous_bid_id"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bids, error) {
	row := q.db.QueryRowContext(ctx, createBid,
		arg.ListingID,
		arg.BuyerID,
		arg.AgentID,
		arg.Amount,
		arg.PreviousBidID,
	)
	var i Bids
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.AgentID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.PreviousBidID,
	)
	return i, err
}

const listBids = `-- name: ListBids :many
SELECT id, listing_id, buyer_id, agent_id, amount, status, created_at, previous_bid_id FROM bids
WHERE buyer_id=$1
`

func (q *Queries) ListBids(ctx context.Context, buyerID int64) ([]Bids, error) {
	rows, err := q.db.QueryContext(ctx, listBids, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bids{}
	for rows.Next() {
		var i Bids
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.AgentID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.PreviousBidID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidsOnListing = `-- name: ListBidsOnListing :many
SELECT id, listing_id, buyer_id, agent_id, amount, status, created_at, previous_bid_id FROM bids
WHERE listing_id=$1
`

func (q *Queries) ListBidsOnListing(ctx context.Context, listingID int64) ([]Bids, error) {
	rows, err := q.db.QueryContext(ctx, listBidsOnListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bids{}
	for rows.Next() {
		var i Bids
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.AgentID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.PreviousBidID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectBid = `-- name: RejectBid :exec
UPDATE bids
SET status = 'rejected'
WHERE id=$1
`

func (q *Queries) RejectBid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, rejectBid, id)
	return err
}
