// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: properties.sql

package database

import (
	"context"
)

const getPropertyByID = `-- name: GetPropertyByID :one
SELECT id, owner, address, city, state, zipcode, bedrooms, bathrooms FROM properties
WHERE id = $1
`

func (q *Queries) GetPropertyByID(ctx context.Context, id int64) (Properties, error) {
	row := q.db.QueryRowContext(ctx, getPropertyByID, id)
	var i Properties
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zipcode,
		&i.Bedrooms,
		&i.Bathrooms,
	)
	return i, err
}
