services:
  dev-db-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=secure-real-estate-app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - dev-db-postgres:/var/lib/postgresql/data
  dev-real-estate-backend:
    container_name: dev-real-estate-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8080:8080"

    depends_on:
      - dev-db-postgres
    entrypoint:
      ["/app/wait-for.sh", "dev-db-postgres:5432", "--", "/app/start.sh"]
    restart: unless-stopped
    # the service should run make watch
    command: ["make", "watch"]

volumes:
  dev-db-postgres: {}
